### ISSUE TITLE
无法动态刷新

### ISSUE THREAD

**Issue by island205** [island205/f5#10]
这是闹那样？

**Comment by island205** [comment]
socket.io.js找不到

**Comment by UncleBill** [comment]
发现了，赶快fix吧

**Comment by island205** [comment]
《-》

**Comment by island205** [comment]
问题已经修改好了，有两个地方有问题，一个是`watch-tree`调用的正则有点问题，还有一个就是读取文件没有过滤掉`/socket.io/socket.io.js`

**Comment by island205** [comment]
@UncleBill   不过还需要整理一下代码
