### ISSUE TITLE
这不是我对这个项目的定位

### ISSUE THREAD

**Issue by island205** [island205/f5#21]
@UncleBill 看到了你开的一个新项目，[crx4f5](https://github.com/UncleBill/crx4f5)，很好，把文件树显示在chrome插件中，可以的话我也来贡献代码。

从你最近提交的几次代码来看，有些代码是为这个插件的使用场景考虑的，虽然我不反对你做这个插件，但是这并不是我这个项目的定位。

我更希望的是用户打开的就是一个简单的网页。

当然这并不是什么冲突，我们可以下面几种方式解决：
1. 你可以在我的项目中开分支出来，专门做与插件配合的f5，而主干还是以我的本意为主；
2. 你可以fork这个项目；
3. 或者修改f5的代码，可以提供一个service出来，你可以在其他项目中调用，使用f5的功能，你还需要的功能可以自己再加；
4. 其他方式，欢迎讨论。

当然如果你觉得我说的不合理，你可以说说你的理由。

**Comment by UncleBill** [comment]
> 我更希望的是用户打开的就是一个简单的网页。

@island205 我觉得用户往往开打的不止一张网页。如果用户打开一张网页后还想打开另一张，就得返回，或者重新开个标签输入`http://localhost:3000/`，这不方便。所以我把链接定向了新窗口，这也方便了在浏览器插件的开发——直接嵌入一个iframe就可以了。
可能你是为了简洁性考虑，大家但都喜欢简洁易用的东西，所以我决定还是开一个`branch`吧

**Comment by UncleBill** [comment]
@island205 我觉得有个扩展还是方便很多的。我把你加到[crx4f5](https://github.com/UncleBill/crx4f5)中了。

**Comment by island205** [comment]
@UncleBill 好，无论是分支还是扩展，我都回来贡献代码的啦。主干我会进行少量的修改，然后就可以发布v0.0.4了。如果以后你是对的，可以再换到主干上来。

**Comment by island205** [comment]
@UncleBill [v0.0.4已经发布](http://island205.com/2012/12/17/f5-v0-0-4-发布/)，你还没开`branch`呀？

**Comment by UncleBill** [comment]
@island205 寝室断网了几天，好久没上来了。

**Comment by island205** [comment]
@UncleBill 哈哈
