### ISSUE TITLE
路径有中文会出现 404 

### ISSUE THREAD

**Issue by zikkeung** [island205/f5#7]
公司的项目都是中文名啊，妹的

**Comment by island205** [comment]
你好，谢谢你提出的bug，这个bug我已经修复了，但是还没发到npm，如果你想现在就用的话：可以把最新的项目克隆出来，在项目根目录运行
    npm install -g
即可

**Comment by zikkeung** [comment]
好滴

在 2012年9月19日 下午1:04，ZhiCun notifications@github.com写道：

**Comment by island205** [comment]
坑爹的是，我的npm帐号无法登陆，所以没办法更新npm线上的版本

**Comment by island205** [comment]
@zikkeung npm 帐号的问题处理了，现在可以在线安装了，支持中文文件名
